# postfix Server Tasks
---
- name: Install postfix package
  ansible.builtin.apt:
    pkg: postfix
    state: present

- name: Ensure postfix service is running
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: yes

- name: Create postfix configuration file
  ansible.builtin.template:
    src: etc/postfix/main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
    owner: root
    group: root
  notify:
    - Restart postfix

- name: Set /etc/mailname
  ansible.builtin.copy:
    content: "{{ _postfix.mailname }}"
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644

- name: Create aliases # noqa args[module]
  register: changed_aliases
  ansible.builtin.lineinfile:
    dest: '/etc/aliases'
    regexp: '^{{ item.user }}:'
    line: '{{ item.user }}: {{ item.address }}'
    state: '{{ item.state }}'
  with_items: "{{ _postfix.aliases }}"
  notify: Convert aliases
