---
- name: Convert aliases
  command: /usr/bin/newaliases
  notify:
    - Reload postfix

- name: Reload postfix
  service:
    name: postfix
    state: reloaded

- name: Restart postfix
  service:
    name: postfix
    state: restarted
