---
- name: Convert aliases
  ansible.builtin.command: /usr/bin/newaliases
  notify:
    - Reload postfix

- name: Reload postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
